version: 1.3
version_base: 1.3

paths:
  raw: './data/raw'
  processed: './data/processed'
  kaggle_owner: 'crowww'
  kaggle_name: 'a-large-scale-fish-dataset'
  save_model_path: './models'


trainer_hyperparameters:
  seed: 42
  max_epochs: 500
  batch_size: 32
  learning_rate: 0.00005
  patience: 30
  check_val_every_n_epoch: 5
  mode: 'min'
  monitor: 'val_loss'
  save_by: "best"
  augment_train: true

wandb_settings:
  entity: 'team-christian'
  project: 'FishEye'
  mode: 'online'

print_cfg: true

profile: True

hydra:
  output_subdir: null
  run:
    dir: .
