on:
  push:
    branches: [ master, main , dvcGcloud]
  pull_request:
    branches: [ master, main , dvcGcloud]

jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Set up Python 3.10.13
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.13
    
    - name: Cache dependencies
      uses: actions/cache@v2
      id:   cache-dependencies
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_tests.txt
    
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with: 
        credentials_json: '${{ secrets.Christian }}'
    
    - uses: iterative/setup-dvc@v1
    - name: DVC Pull
      run: dvc pull --verbose 

    - name: Test with pytest
      run: |
        pip install pytest
        pytest -v