on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test: 

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.10.13
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.13
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_tests.txt
    
    - uses: iterative/setup-dvc@v1
    - name: Get data
      run: dvc pull
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.DATA_BUCKET_SECRET }}

    - name: Test with pytest
      run: |
        pip install pytest
        pytest -v